첫번째 문자열 계산기
Java-Bom/calculator pull request #11
Opened 2020-04-21 10:17 UTC by BangKiHyun

첫번째 문자열 계산기입니다!

2020-04-21 12:38 UTC, csbsjy commented on src/main/java/calculator/Separator.java
> +    public String[] getArrayOperation() {
변수가 초기화되지 않은 상태에서도 get 할 수 있게 public 으로 열려있는데, init 을 먼저 해야하는지 모르는 클라이언트가 get 메서드를 사용하게되면 어떤 문제가 발생할 수 있을지 생각해보면 좋을 것 같습니다 !

2020-04-21 12:38 UTC, csbsjy commented on src/main/java/calculator/AddOperation.java
> +public class AddOperation implements Operation {
연산이 추가될 때마다 Operation의 구현체를 추가해야하고 AddOperation 의 연산이 바뀌면 구현체를 또 추가해야해서 후에 관리가 힘들지 않을까라는 생각이 듭니다 !

2020-04-21 12:38 UTC, csbsjy commented on src/main/java/calculator/Calculator.java
> +        mapping.init();
OperationMapping 객체의 초기화를 Calculator 에서 해야할까요? 자신의 상태는 자신이 관리하는 것이 좋다고 생각합니다 !

2020-04-21 12:38 UTC, csbsjy commented on src/main/java/calculator/OperationMapping.java
> +        operations.put("+", new AddOperation());
연산이 추가될 수록, Operation 의 구현체, OperationMapping 의 init메서드도 함께 추가되어야해서 휴먼에러의 가능성도 높지 않을까 라는 생각이들어요!

2020-04-21 12:38 UTC, csbsjy commented on src/main/java/calculator/Split.java
> +            throw new NumberFormatException();
잡은 에러를 그냥 다시 던지기보다 조금 더 특정할 수 있는 에러메시지를 함께 던져주는게 좋지 않을까요?

2020-04-21 12:38 UTC, csbsjy commented on src/test/java/calculator/CalculatorTest.java
> +        calculator.calculate("3 / 0");
assertThatThrownBy() static 메서드를 사용하면 더 명시적으로 확인할 수 있어요!

2020-04-21 12:38 UTC, csbsjy commented on src/test/java/calculator/SeparatorTest.java
> +    }
double[] operand = separator.getArrayOperand(); 
로 받고, 
double[] expectOperand = { 2.0, 5.0, 7.0, 6.0} ;
과 같이하고 비교하면 더 믿을 수 있는 테스트가 될 것 같아요 ~

2020-04-21 13:23 UTC, pci2676 requested changes
조금 더 객체간 메세지를 던지도록 수정해보면 어떨까요?

2020-04-21 13:23 UTC, pci2676 commented on src/test/java/calculator/CalculatorTest.java
> +    }
`@ParameterizedTest`와 `@CsvSource`를 이용해서 간단하게 바꿔볼수 있을것 같아

2020-04-21 13:23 UTC, pci2676 commented on src/main/java/calculator/Split.java
> +    }
`OperationMapping`에게 메세지를 전달하도록 바꿔보면 어떨까?

2020-04-21 13:23 UTC, pci2676 commented on src/main/java/calculator/Separator.java
> +    }
`operand`와 `operation`을 배열로 관리하고 있네!
배열이 아닌 List를 이용한다면 어떠한 이점이 있을까?

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/main/java/calculator/AddOperation.java
> +public class AddOperation implements Operation {
이건 오히려 잘 구현한 것 같네요. 인터페이스 정의해서 구현을 잘 감춘것 같아서 이런 구현은 확장하기 좋은 구현이에요.

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/main/java/calculator/OperationMapping.java
> +        operations.put("+", new AddOperation());
이 구현도 나쁘지 않아 보이고, 좀 더 좋은방법은 이 Mapping클래스의 맵을 전역 상수로 관리하고,
OperationMapping클래스의 생성자를 감춰버리는게 더 좋아보여요.
 operations 하나만 존재하면 되니까 다른곳에서 더 생성하지 못하도록 막아야 해요.

제일 깔끔하게 구현하려면 enum을 활용하는 것도 좋겠네요

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/main/java/calculator/Split.java
> +            checkLength(texts);
length를 while문 돌때마다 체크하네요

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/main/java/calculator/OperationMapping.java
> +        return operations.get(operation);
없는 문자열이 들어오면 해당 함수를 쓰는 쪽이 nullpointexception이 발생한 수 있는 코드네요
Optional로 리턴해도 좋을거같아요

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/test/java/calculator/CalculatorTest.java
> +import org.junit.Before;
junit4와 jupiter(junit5)를 같이 사용하고 있는데, 이거 실행은 되나요?
jupiter(junit5)로 다 교체하는게 좋아요

2020-04-21 16:39 UTC, chldbtjd2272 commented on src/main/java/calculator/Split.java
> +    private static final String PLUS = "+";
OperationMapping에 operation이 하나 추가될때마다 상수하나가 추가되겠네요.
이것보단 OperationMapping에 함수를 하나 뚤어서 사용하는게 좋아보이네요

2020-04-22 04:15 UTC, BangKiHyun commented on src/main/java/calculator/Separator.java
> +    public String[] getArrayOperation() {
아 그렇네요! 감사합니다! 수정해보겠습니다!

2020-04-22 04:17 UTC, BangKiHyun commented on src/main/java/calculator/Calculator.java
> +        mapping.init();
감사합니다! 수정해보겠습니다!

2020-04-22 04:22 UTC, BangKiHyun commented on src/main/java/calculator/OperationMapping.java
> +        operations.put("+", new AddOperation());
오 감사합니다! 공부해서 수정해보겠습니다!

2020-04-22 04:24 UTC, BangKiHyun commented on src/main/java/calculator/Split.java
> +            throw new NumberFormatException();
좋은지적 감사합니다! 수정하겠습니다!

2020-04-22 04:25 UTC, BangKiHyun commented on src/test/java/calculator/CalculatorTest.java
> +        calculator.calculate("3 / 0");
오 공부해서 적용해보도록 하겠습니다!

2020-04-22 04:26 UTC, BangKiHyun commented on src/test/java/calculator/SeparatorTest.java
> +    }
오 맞습니다! 수정하겠습니다!

2020-04-22 04:27 UTC, BangKiHyun commented on src/test/java/calculator/CalculatorTest.java
> +    }
아하 공부해서 적용해보겠습니다 ㅎㅎ

2020-04-22 04:28 UTC, BangKiHyun commented on src/main/java/calculator/Separator.java
> +    }
아 List가 더 편리하겠네요ㅎㅎ 바로 수정하겠습니다!

2020-04-22 04:30 UTC, BangKiHyun commented on src/main/java/calculator/Split.java
> +            checkLength(texts);
앗! 감사합니다! 수정하겠습니다!

2020-04-22 04:37 UTC, BangKiHyun commented on src/main/java/calculator/OperationMapping.java
> +        return operations.get(operation);
split할 때 Map의 Key값에 없는 문자열이 들어올 시 Exception을 던지게 해도 될까요?

2020-04-22 04:39 UTC, BangKiHyun commented on src/test/java/calculator/CalculatorTest.java
> +import org.junit.Before;
아 감사합니다! 수정하겠습니다!

2020-04-22 04:40 UTC, BangKiHyun commented on src/main/java/calculator/Split.java
> +    }
아 그렇네요 ㅎㅎ 감사합니다 수정하겠습니다!

2020-04-22 04:41 UTC, BangKiHyun commented on src/main/java/calculator/Split.java
> +    private static final String PLUS = "+";
오 좋은 지적 감사합니다! 수정하겠습니다!

2020-04-22 12:06 UTC, mjung1798 commented on src/test/java/calculator/CalculatorTest.java
> +    @ValueSource(strings = {"6 + 2 + 1"})
더하기 연산을 수행한다에 인자값이 3개가 들어가는이유는 뭔가요?

2020-04-22 12:06 UTC, mjung1798 commented on src/main/java/calculator/OperationTypeMapping.java
> +    private static Map<String, OperationType> operationType = new HashMap<>();
map 쓰는것도 좋네요 :)
Enum의 valueOf() 한번 찾아보시겠어요? 다른 방법도 있다는걸 알려드리고 싶어서요 :)

2020-04-22 12:06 UTC, mjung1798 commented on src/main/java/calculator/Calculator.java
> +    private double operate(List<Double> operands, List<String> operations) {
이부분 읽기가 조금 힘든 것 같습니다! set() 부분 인자가 3개인데 다른 방법은 없을까요?

2020-04-22 13:31 UTC, BangKiHyun commented on src/test/java/calculator/CalculatorTest.java
> +    @ValueSource(strings = {"6 + 2 + 1"})
아 크게 의미는 없습니다! 의식의 흐름대로 했던 것 같습니다!

2020-04-22 13:31 UTC, BangKiHyun commented on src/main/java/calculator/OperationTypeMapping.java
> +    private static Map<String, OperationType> operationType = new HashMap<>();
오 감사합니다! Enum의 valueOf() 공부해서 적용해보겠습니다!

2020-04-22 13:34 UTC, BangKiHyun commented on src/main/java/calculator/Calculator.java
> +    private double operate(List<Double> operands, List<String> operations) {
좀 더 나은 방법으로 수정해보겠습니다!

2020-04-22 13:35 UTC, mjung1798 commented on src/main/java/calculator/OperationTypeMapping.java
> +    private static Map<String, OperationType> operationType = new HashMap<>();
https://www.baeldung.com/java-enum-values

2020-04-23 09:29 UTC, mjung1798 commented on src/main/java/Main.java
> +        Calculator calculator = new Calculator(value);
엇..! 이건 바꾸기 전이 더 나은거 같아요!!!
이런 식이면 N개의 계산을 한다고 했을 때마다 Calulator를 새로 만들어야 한다는 의미가 되는데,
이전 방식은 1개의 계산기를 만들어 두었을 때 text만 입력하면 계산을 할 수 있다가 되니까요!!

2020-04-23 09:45 UTC, BangKiHyun commented on src/main/java/Main.java
> +        Calculator calculator = new Calculator(value);
아 그렇네요! 감사합니다! 수정하겠습니다!

2020-04-23 14:12 UTC, csbsjy reviewed
어떤 객체는 상태가 필요하고 어떤 애는 필요하지 않은건지 판단하는건 어려워요 ~_~

2020-04-23 14:12 UTC, csbsjy commented on src/main/java/calculator/Separator.java
> +}
Separator 가 text 와 splitter 를 상태로 가져아하는 이유가 있을까요? 
제 생각에는 Separator 는 SeparatedValue 를 반환하는 역할만 있는 것 같은데, separateOperandAndOperation 에서 text 만 받고 SeparatedValue 를 반환해도 충분하지 않을까 싶어요.
그렇게하면 상태를 가지지 않기 때문에 static 메서드 작성이 가능할 것 같고 new Sepator(text).separateOperandAndOperation() 대신 Separator.separateOperandAndOperation(text) 로 인스턴스 생성을 안할 수도 있겠어요.

Calculator 메서드 보다가 Separator 가 계속 생성되는 것이 어색해보여서 남겨봅니다 !

2020-04-23 14:12 UTC, csbsjy commented on src/main/java/calculator/Splitter.java
> +    private String text;
Splitter 도 text 를 상태로 가지고 있고 생성자로 받기 때문에 새로운 계산이 주어질 때마다 새로 생성해야하는 객체가 되었어요. 물론 지금 요구사항은 계산을 한번만 하고 말지만, 일반적인 계산기는 그러지 않으니까요 !

2020-04-24 05:59 UTC, BangKiHyun commented on src/main/java/calculator/Separator.java
> +}
오 감사합니다! 이렇게 또 하나 배워갑니다!

2020-04-24 06:02 UTC, BangKiHyun commented on src/main/java/calculator/Splitter.java
> +    private String text;
생각이 너무 짧았던거 같습니다! 수정하겠습니다!

2020-04-25 09:16 UTC, merged