첫번째 문자열 계산기
Java-Bom/calculator pull request #12
Opened 2020-04-22 11:23 UTC by NDjust

첫번째 문자열 계산기입니다. 

피드백 부탁드립니다!

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/Calculator.java
> +            if (operatorSymbol.equals("+")) { result = Operation.PLUS.apply(x, y); }
이렇게 if 문을 쓰면 Enum을 사용한 이유가 없는것 같습니다
Enum의 valueOf() 메서드를 찾아보세요

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +    public List<String> operators;
public class에서 public 멤버변수는 지향해야합니다.
다른 클래스에서 이 멤버변수를 제약없이 막 바꿀 수 있으니까요

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +    public boolean isNumeric(String value) {
이 클래스에서만 사용하는 메서드라면 private으로 바꿔주세요.

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +            if (isNumeric(value)) { numbers.add(Double.parseDouble(value)); }
이걸 이렇게 한이유는,,? 너무 가독성이 떨어지는것같아요

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +    public boolean isNumeric(String value) {
그리고 보통 음,, 그리고 Number formatException이 터지는데 boolean return이 이상해요. 
의도는 + -를 구분하기 위해서인것 같은데 만약 ㄱ ㄴ ㄷ 과같이 검증되지 않은 값이 들어오면 이상합니다.
이런 값에 대한 검증에 대해서 parseDouble로 체킹하는게 부적합합니다.

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +public class InputProcessor {
InputProcessor라는 이름이 의미가 명확하지 않아요 중의적입ㄴ디ㅏ.
InputProcessor라서 scanner input 을 받는 역할일거라 생각했는데 아니었습니다.

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/operation/Operation.java
> +    public static void main(String[] args) {
이코드는 왜있는거죠?

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +        if (values.length == 1 && values[0].equals("")) {
value.length == 1 인게 왜 입력값이 없는건가요??
이런 부분이 명확하지 않으면 조건식을 변수명으로 빼서 조건식이 의미하는 바를 작성해주어도 좋습니다.

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/Calculator.java
> +public class Calculator {
이 클래스에 너무 많은 역할이 있어요.
- 사용자 입력받기
- 연산자와 숫자 출력하기
- 실제 계산하기 
- 심볼 분류하기
이 클래스에 모든게 몰빵되어있고, main에서 run()을 부르는데 클래스의 역할이 명확하게 분리된 것도 아니고
사실상 모든 로직을 여기서 해결하는 느낌이에요

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/Calculator.java
> +        List<String> operators = processor.operators;
아래서 말했듯이 이런식으로, processor안에 있는 멤버변수를 여기서 다룰 수 있어 원래 processor라는 객체가 의도하고자 하는 바를 수행할 수 없습니다.

``processor.operators = new ArrayList<>(Arrays.asList("a", "b", "c"));``

이런식으로 원래 예측하지 못했던 행동을 할 수 있으니까요.

2020-04-22 11:52 UTC, mjung1798 commented on src/main/java/Calculator.java
> +        String[] values = value.split(" ");
split하는 이 spliter가 의미하를 써주면 좋을 것 같습니다
``private static final String BLANK = " ";``
이런식으로 상수로 빼주면 코드의 의미가 명확해집니다.

2020-04-22 12:04 UTC, csbsjy commented on src/test/java/CalculatorTest.java
> +    @DisplayName("실제 연산이 잘 수행되는지 확인!")
@DisplayName 안의 메시지는 어떤걸 테스트하는지 더 명시적으로 하는게 좋다고 하더라구요, 테스트만 보고 요구사항이 뭔지 파악할수 있게 하는 것이 좋다는 가르침이 내려오고있습니당

2020-04-22 12:04 UTC, csbsjy commented on src/test/java/input/InputProcessorTest.java
> +        assertThat(3).isEqualTo(operators.size());
assertThat 을 사용하면 앞에 하나만 실패해도 뒤의 테스트를 수행하지 않는데, assertAll 을 사용하면 모든 assert 구문을 테스트할 수 있어요.

2020-04-22 12:04 UTC, csbsjy commented on src/main/java/Calculator.java
> +            if (operatorSymbol.equals("+")) { result = Operation.PLUS.apply(x, y); }
https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2020-04-22 12:04 UTC, csbsjy commented on src/test/java/operation/OperationTest.java
> +    public void testApply() throws Exception {
@CsvSource, @ParameterizedTest 를 사용하면 더 간단하게 작성할 수 있을 것 같아요

2020-04-22 12:04 UTC, csbsjy commented on src/main/java/Calculator.java
> +public class Calculator {
외부에 노출되는 메서드는 run 뿐인데 다 public 으로 열려있네요!

2020-04-22 12:07 UTC, mjung1798 commented on src/main/java/input/InputProcessor.java
> +            if (isNumeric(value)) { numbers.add(Double.parseDouble(value)); }
아 이거말고 아래 eles if줄

2020-04-22 12:14 UTC, mjung1798 commented on src/main/java/operation/Operation.java
> +    public static void main(String[] args) {
엇 화안났어요 이코드 불필요한것 같습니다..ㅎㅎ

2020-04-22 13:28 UTC, pci2676 requested changes
안녕하세요!
첫번째 미션 수행하느라 고생하셨어요.
간단하게 수정 할 만한 부분 남겼으니 확인해주세요!
따로 궁금한 점 있으면 슬랙이나 단톡방에 메세지 주세요!

2020-04-22 13:28 UTC, pci2676 commented on src/main/java/Calculator.java
> +        processor.splitOperatorsAndNumbers(values);
검사와 분리가 따로 이루어지고 있네요!
코드의 응집도가 떨어진다고 볼 수 있는데요.
이러한 경우 어떠한 문제가 발생할 수 있는지 한 번 생각해 보면 좋을것 같아요!

2020-04-22 13:28 UTC, pci2676 commented on src/main/java/input/InputProcessor.java
> +    }
`1 + + 1 1`과 같은 입력이 들어올 경우에 대해 생각해 보시면 좋을 것 같아요

2020-04-22 13:28 UTC, pci2676 commented on src/main/java/input/InputProcessor.java
> +        }
Exception을 흐름을 제어하기 위해 사용하시는 것은 **지양**하시는게 좋습니다.
`이펙티브 자바 69장. 예외는 진짜 예외 상황에서만 사용하라`
를 참고해보면 좋을 것 같아요.

2020-04-22 13:28 UTC, pci2676 commented on src/main/java/input/InputProcessor.java
> +        }
입력값이 숫자인지 아닌지 확인하는 것은 정규표현식을 활용해 보시는 것도 좋을 것 같네요!

2020-04-22 13:28 UTC, pci2676 commented on src/main/java/Calculator.java
> +public class Calculator {
객체지향 설계원칙중 하나인 단일 책임 원칙을 한번 찾아보시는 것도 좋을 것 같아요.
한 가지 클래스는 한 가지 역할만 가지도록 설계를 좀 더 세분화 해보는건 어떨까요?
그리고 객체간 메서드를 호출(=메세지를 전달)하는 방식으로 설계를 수정해보시면 좋을 것 같아요.

2020-04-22 13:36 UTC, mjung1798 commented on src/main/java/Calculator.java
> +            if (operatorSymbol.equals("+")) { result = Operation.PLUS.apply(x, y); }
https://www.baeldung.com/java-enum-values

2020-04-23 02:19 UTC, csbsjy commented on src/test/java/input/InputProcessorTest.java
> +        assertThat(3).isEqualTo(operators.size());
잘못된 input 이 들어왔을 때의 테스트가 없어요!

2020-04-23 02:19 UTC, csbsjy commented on src/test/java/input/InputProcessorTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class,() -> processor.validInputString(values));
이건 무엇을 테스트하려는건가요?

2020-04-23 02:19 UTC, csbsjy commented on src/test/java/CalculatorTest.java
> +        assertThat(10.0).isEqualTo(result);
계산기 테스트지만 입력값을 쪼개는 것부터 시작하고 있어요. Calculator에 넘겨줄 operators 와 numbers 를 given 으로 주는 것 부터 시작하면 될 것 같은데, inputprossor 테스트도 함께 하는 느낌? @pci2676  어떻게 생각하시나요, 저는 테스트코드에 아직 미숙하여 잘 판단이 서지 않습니다.

2020-04-23 06:29 UTC, pci2676 commented on src/test/java/CalculatorTest.java
> +        assertThat(10.0).isEqualTo(result);
@csbsjy 저도 동의합니다!
이전 저도 다른 리뷰어에게 피드백을 받은적이 있는 내용입니다. 
더 단순하게 검증을 할 수 있으면 좋을것 같아요.
테스트는 **구현을 모르게** 작성이 되어야한다고 생각합니다.

2020-04-23 07:31 UTC, NDjust commented on src/main/java/Calculator.java
> +            if (operatorSymbol.equals("+")) { result = Operation.PLUS.apply(x, y); }
자료 공유 감사합니다! enum에 익숙치 않아 이도저도 안되는 코드를 짰네요 ㅠㅠ 조언 갑사합니다!

2020-04-23 07:31 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +    public boolean isNumeric(String value) {
네! 좀 더 명확하고 안전한 코드로 변경하겠습니다. 피드백 감사합니다!

2020-04-23 07:32 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +public class InputProcessor {
네 해당 객체의 역활을 정확히 정의한 후에 이름을 짓고, 코드를 작성하면서 다듬어야겠네요 ㅠㅠ 감사합니다!

2020-04-23 07:32 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +        if (values.length == 1 && values[0].equals("")) {
빈 값이 들어올 경우 처리를 할려고 했는데, 좀 더 명확하게 작성하겠습니다.

2020-04-23 07:33 UTC, NDjust commented on src/main/java/Calculator.java
> +public class Calculator {
@pci2676 님께서 같이 조언해주신 단일 책임 원칙에 대해 공부하고 수정해보겠습니다. 조언 감사합니다!

2020-04-23 07:34 UTC, NDjust commented on src/test/java/CalculatorTest.java
> +    @DisplayName("실제 연산이 잘 수행되는지 확인!")
아하 넵 감사합니다! 제가 테스트 코드를 거의 작성해본 경험이 없어, 관련 자료나 좋은 사례를 찾아가면서 수정하겠습니다!

2020-04-23 07:34 UTC, NDjust commented on src/main/java/Calculator.java
> +        processor.splitOperatorsAndNumbers(values);
아하 네! 좋은 조언 감사합니다!

2020-04-23 07:37 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +    }
@pci2676 궁금한 점이 한 가지 있는데, 해당 미션 문자열 입력은 위와 같이 올바르지 않은 계산식이 들어오는 경우도 처리할 수 있도록 구현하면 되는 건가요?? 미션 정의가 약간 헷갈립니다!

2020-04-23 07:37 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +        }
네! 정규표현식으로 깔끔하게 처리하는게 좋을 거 같습니다! 감사합니다~~

2020-04-23 07:38 UTC, NDjust commented on src/main/java/Calculator.java
> +public class Calculator {
네넵 제가 객체지향 관련 원칙에 대한 지식이 많이 부족해 찾아보면서 공부하고 수정해보겠습니다!

2020-04-23 07:39 UTC, NDjust commented on src/test/java/input/InputProcessorTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class,() -> processor.validInputString(values));
잘못된 input의 경우도 처리하도록 구현하고 테스트 케이스도 추가하겠습니다 감사합니다!


위 테스트는 입력값이 없는 경우 작성한 예외코드가 동작하는지 확인하는 테스트입니다!

2020-04-23 07:40 UTC, NDjust commented on src/test/java/CalculatorTest.java
> +        assertThat(10.0).isEqualTo(result);
아하 테스트도 단위당 정확하게 분리해서 테스트하는 연습 하도록 하겠습니다! 감사합니다.

2020-04-23 08:19 UTC, pci2676 commented on src/main/java/input/InputProcessor.java
> +    }
올바르지 않은 계산식은 처리하지 않고 Exception을 발생시키는게 맞습니다!
일반적인 계산기는 잘못된 수식을 계산하지 않으니까요!

2020-04-23 08:34 UTC, NDjust commented on src/main/java/input/InputProcessor.java
> +    }
@pci2676 아 넵 감사합니다!

2020-04-23 11:12 UTC, chldbtjd2272 commented on src/main/java/Calculator.java
> +        return numbers.remove(0);
함수 파라미터로 받은 리스트에 특정 값을 추가하거나 제거하는 것은 안좋습니다.
이 함수 안해서 numbers 리스트를 조작하게 되면 이 함수를 호출한 쪽 리스트도 다 바뀌게 되어 예상하기 힘든 코드가 됩니다.
list의 값을 변경하는 것 보단 리스트의 값을 조회만해서 변수에 담아 결과를 반환하도록 하는게 좋을거 같네요

2020-04-23 11:12 UTC, chldbtjd2272 commented on src/main/java/input/InputProcessor.java
> +    public void validInputString(String[] values) {
이 함수는 splitOperatorsAndNumbers 안에서 호출하도록 하는게 좋을거 같아요
이 클래스를 사용하는 쪽은 항상 valid함수 호출하고 split을 해야하는 상황이 생기네요.
split하기 전에는 항상 valid를 체크해야하니 구현을 안쪽으로 숨기세요

2020-04-26 11:00 UTC, merged